# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('info', models.CharField(max_length=150, verbose_name='文章简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('location', models.CharField(max_length=80, verbose_name='所属地理位置')),
                ('image', models.ImageField(upload_to='img/', verbose_name='美食图片')),
            ],
            options={
                'verbose_name': '美食表',
                'verbose_name_plural': '美食表',
                'db_table': 'food',
            },
        ),
    ]
