# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-18 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('info', models.CharField(max_length=90, verbose_name='文章简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('location', models.CharField(max_length=80, verbose_name='所属地理位置')),
                ('image', models.ImageField(upload_to='img/', verbose_name='美食图片')),
                ('foodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'verbose_name': '美食表',
                'verbose_name_plural': '美食表',
                'db_table': 'food',
            },
        ),
    ]
